# Generated by Django 5.2.7 on 2025-10-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_store_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
