# Generated by Django 5.2.7 on 2025-10-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
