<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-25 12:15
=======
# Generated by Django 5.2.7 on 2025-10-23 12:23
>>>>>>> master

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_placetype_alter_fitnessspot_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Komunitas',
                'verbose_name_plural': 'Kategori Komunitas',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama komunitas olahraga', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi singkat komunitas')),
<<<<<<< HEAD
                ('contact_info', models.CharField(blank=True, help_text='Kontak admin komunitas', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(blank=True, help_text='Admin yang bisa mengelola komunitas', related_name='managed_communities', to=settings.AUTH_USER_MODEL)),
                ('fitness_spot', models.ForeignKey(help_text='Tempat kebugaran tempat komunitas ini sering berlatih', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='home.fitnessspot')),
                ('founder', models.ForeignKey(help_text='Pembuat dan pemilik utama komunitas', on_delete=django.db.models.deletion.CASCADE, related_name='founded_communities', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(help_text='Anggota komunitas', related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Kategori komunitas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='community.communitycategory')),
=======
                ('contact_info', models.CharField(blank=True, help_text='Kontak admin komunitas (bisa berupa Instagram, nomor WA, dll)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_communities', to=settings.AUTH_USER_MODEL)),
                ('fitness_spot', models.ForeignKey(help_text='Tempat kebugaran tempat komunitas ini sering berlatih', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='home.fitnessspot')),
                ('members', models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Kategori komunitas (misalnya: gym, futsal, yoga)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='community.communitycategory')),
>>>>>>> master
            ],
            options={
                'verbose_name': 'Komunitas',
                'verbose_name_plural': 'Komunitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keanggotaan Komunitas',
                'verbose_name_plural': 'Keanggotaan Komunitas',
                'ordering': ['-joined_at'],
                'unique_together': {('community', 'user')},
            },
        ),
=======
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community')),
            ],
        ),
>>>>>>> master
    ]
