# Generated by Django 5.2.7 on 2025-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
