# Generated by Django 5.2.7 on 2025-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_community_admin_community_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto profil komunitas', null=True, upload_to='community_images/'),
        ),
    ]
