# Generated by Django 5.2.7 on 2025-10-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategori komunitas (misalnya: gym, futsal, yoga)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='community.communitycategory'),
        ),
    ]
