# Generated by Django 5.2.7 on 2025-12-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='schedule',
            field=models.TextField(blank=True, help_text='Tulis jadwal dipisah baris baru. Contoh: Senin 10:00 - Lari Pagi', null=True),
        ),
    ]
