# Generated by Django 5.2.7 on 2025-12-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('Running', 'Running'), ('Futsal', 'Futsal'), ('Basketball', 'Basketball'), ('Badminton', 'Badminton'), ('Tennis', 'Tennis'), ('Cycling', 'Cycling'), ('Yoga', 'Yoga'), ('General', 'General')], default='General', help_text='Kategori komunitas (misalnya: gym, futsal, yoga)', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Tagline pendek di bawah judul', max_length=150),
        ),
        migrations.DeleteModel(
            name='CommunityCategory',
        ),
    ]
