# Generated by Django 5.2.7 on 2025-12-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_category_community_short_description_and_more'),
        ('home', '0002_placetype_alter_fitnessspot_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at'], 'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('Aerobics', 'Aerobics'), ('Aikido', 'Aikido'), ('Archery', 'Archery'), ('Athletics', 'Athletics'), ('Badminton', 'Badminton'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Billiards', 'Billiards'), ('BMX', 'BMX'), ('Bodybuilding', 'Bodybuilding'), ('Bowling', 'Bowling'), ('Boxing', 'Boxing'), ('Calisthenics', 'Calisthenics'), ('Canoeing', 'Canoeing'), ('Capoeira', 'Capoeira'), ('Cheerleading', 'Cheerleading'), ('Climbing', 'Climbing'), ('Cricket', 'Cricket'), ('CrossFit', 'CrossFit'), ('Cycling', 'Cycling'), ('Dance', 'Dance'), ('Dodgeball', 'Dodgeball'), ('Equestrian', 'Equestrian'), ('Fencing', 'Fencing'), ('Floorball', 'Floorball'), ('Football', 'Football'), ('Futsal', 'Futsal'), ('General', 'General'), ('Golf', 'Golf'), ('Gymnastics', 'Gymnastics'), ('Handball', 'Handball'), ('HIIT', 'HIIT'), ('Hiking', 'Hiking'), ('Hockey', 'Hockey'), ('Ice Skating', 'Ice Skating'), ('Judo', 'Judo'), ('Ju-Jitsu', 'Ju-Jitsu'), ('Karate', 'Karate'), ('Kayaking', 'Kayaking'), ('Kickboxing', 'Kickboxing'), ('Kung Fu', 'Kung Fu'), ('Lacrosse', 'Lacrosse'), ('Marathon', 'Marathon'), ('MMA', 'MMA'), ('Motocross', 'Motocross'), ('Muay Thai', 'Muay Thai'), ('Netball', 'Netball'), ('Paddle', 'Paddle'), ('Parkour', 'Parkour'), ('Pilates', 'Pilates'), ('Polo', 'Polo'), ('Powerlifting', 'Powerlifting'), ('Rowing', 'Rowing'), ('Rugby', 'Rugby'), ('Running', 'Running'), ('Sailing', 'Sailing'), ('Sepak Takraw', 'Sepak Takraw'), ('Shooting', 'Shooting'), ('Skateboarding', 'Skateboarding'), ('Skating', 'Skating'), ('Skiing', 'Skiing'), ('Snowboarding', 'Snowboarding'), ('Softball', 'Softball'), ('Squash', 'Squash'), ('Surfing', 'Surfing'), ('Swimming', 'Swimming'), ('Table Tennis', 'Table Tennis'), ('Taekwondo', 'Taekwondo'), ('Tai Chi', 'Tai Chi'), ('Tennis', 'Tennis'), ('Track & Field', 'Track & Field'), ('Trail Running', 'Trail Running'), ('Triathlon', 'Triathlon'), ('Ultimate Frisbee', 'Ultimate Frisbee'), ('Volleyball', 'Volleyball'), ('Walking', 'Walking'), ('Water Polo', 'Water Polo'), ('Weightlifting', 'Weightlifting'), ('Wrestling', 'Wrestling'), ('Yoga', 'Yoga'), ('Zumba', 'Zumba')], default='General', help_text='Community category (e.g., Gym, Futsal, Yoga)', max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Admin contact info (e.g., Instagram handle, WhatsApp number)', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(help_text='Detailed description of the community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='fitness_spot',
            field=models.ForeignKey(help_text='Fitness spot where this community usually trains', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='home.fitnessspot'),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, help_text='Community profile picture', null=True, upload_to='community_images/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Name of the sports community', max_length=200),
        ),
        migrations.AlterField(
            model_name='community',
            name='schedule',
            field=models.TextField(blank=True, help_text='Write schedule separated by new lines. Example: Monday 19:00 - Night Run', null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short tagline displayed below the title', max_length=150),
        ),
    ]
