# Generated by Django 5.2.7 on 2025-10-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessSpot',
            fields=[
                ('place_id', models.CharField(help_text='ID unik dari Google Places API', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Nama tampilan tempat', max_length=255)),
                ('types', models.JSONField(blank=True, help_text='Daftar kategori tempat dari Google', null=True)),
                ('address', models.TextField(help_text='Alamat lengkap yang diformat')),
                ('phone_number', models.CharField(blank=True, help_text='Nomor telepon nasional', max_length=50, null=True)),
                ('website', models.URLField(blank=True, help_text='URL situs web resmi', max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Koordinat Lintang (Latitude)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Koordinat Bujur (Longitude)', max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating rata-rata tempat (1.0 - 5.0)', max_digits=8, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Jumlah total ulasan pengguna')),
            ],
            options={
                'verbose_name': 'Tempat Kebugaran',
                'verbose_name_plural': 'Tempat Kebugaran',
                'ordering': ['-rating_count', 'name'],
            },
        ),
    ]
