# Generated by Django 5.2.7 on 2025-10-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('name', models.CharField(help_text="Nama jenis tempat dari Google API (misalnya, 'gym')", max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis Tempat',
                'verbose_name_plural': 'Jenis-Jenis Tempat',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='fitnessspot',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating rata-rata tempat (1.0 - 5.0)', max_digits=3, null=True),
        ),
        migrations.RemoveField(
            model_name='fitnessspot',
            name='types',
        ),
        migrations.AddField(
            model_name='fitnessspot',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='Kategori tempat dari Google', to='home.placetype'),
        ),
    ]
