# Generated by Django 5.2.7 on 2025-10-23 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_placetype_alter_fitnessspot_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('starting_date', models.DateTimeField(db_index=True)),
                ('ending_date', models.DateTimeField(db_index=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='events', to='home.fitnessspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
